// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/redpanda/stock.proto

package nasdaq.historical.v1;

public final class Stock {
  private Stock() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NasdaqHistoricalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nasdaq.historical.v1.NasdaqHistorical)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string last = 2;</code>
     * @return The last.
     */
    java.lang.String getLast();
    /**
     * <code>string last = 2;</code>
     * @return The bytes for last.
     */
    com.google.protobuf.ByteString
        getLastBytes();

    /**
     * <code>float volume = 3;</code>
     * @return The volume.
     */
    float getVolume();

    /**
     * <code>string open = 4;</code>
     * @return The open.
     */
    java.lang.String getOpen();
    /**
     * <code>string open = 4;</code>
     * @return The bytes for open.
     */
    com.google.protobuf.ByteString
        getOpenBytes();

    /**
     * <code>string high = 5;</code>
     * @return The high.
     */
    java.lang.String getHigh();
    /**
     * <code>string high = 5;</code>
     * @return The bytes for high.
     */
    com.google.protobuf.ByteString
        getHighBytes();

    /**
     * <code>string low = 6;</code>
     * @return The low.
     */
    java.lang.String getLow();
    /**
     * <code>string low = 6;</code>
     * @return The bytes for low.
     */
    com.google.protobuf.ByteString
        getLowBytes();
  }
  /**
   * Protobuf type {@code nasdaq.historical.v1.NasdaqHistorical}
   */
  public static final class NasdaqHistorical extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nasdaq.historical.v1.NasdaqHistorical)
      NasdaqHistoricalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NasdaqHistorical.newBuilder() to construct.
    private NasdaqHistorical(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NasdaqHistorical() {
      date_ = "";
      last_ = "";
      open_ = "";
      high_ = "";
      low_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NasdaqHistorical();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NasdaqHistorical(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              last_ = s;
              break;
            }
            case 29: {

              volume_ = input.readFloat();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              open_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              high_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              low_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nasdaq.historical.v1.Stock.internal_static_nasdaq_historical_v1_NasdaqHistorical_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nasdaq.historical.v1.Stock.internal_static_nasdaq_historical_v1_NasdaqHistorical_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nasdaq.historical.v1.Stock.NasdaqHistorical.class, nasdaq.historical.v1.Stock.NasdaqHistorical.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_FIELD_NUMBER = 2;
    private volatile java.lang.Object last_;
    /**
     * <code>string last = 2;</code>
     * @return The last.
     */
    @java.lang.Override
    public java.lang.String getLast() {
      java.lang.Object ref = last_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        last_ = s;
        return s;
      }
    }
    /**
     * <code>string last = 2;</code>
     * @return The bytes for last.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastBytes() {
      java.lang.Object ref = last_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        last_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOLUME_FIELD_NUMBER = 3;
    private float volume_;
    /**
     * <code>float volume = 3;</code>
     * @return The volume.
     */
    @java.lang.Override
    public float getVolume() {
      return volume_;
    }

    public static final int OPEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object open_;
    /**
     * <code>string open = 4;</code>
     * @return The open.
     */
    @java.lang.Override
    public java.lang.String getOpen() {
      java.lang.Object ref = open_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        open_ = s;
        return s;
      }
    }
    /**
     * <code>string open = 4;</code>
     * @return The bytes for open.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOpenBytes() {
      java.lang.Object ref = open_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        open_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HIGH_FIELD_NUMBER = 5;
    private volatile java.lang.Object high_;
    /**
     * <code>string high = 5;</code>
     * @return The high.
     */
    @java.lang.Override
    public java.lang.String getHigh() {
      java.lang.Object ref = high_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        high_ = s;
        return s;
      }
    }
    /**
     * <code>string high = 5;</code>
     * @return The bytes for high.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHighBytes() {
      java.lang.Object ref = high_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        high_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOW_FIELD_NUMBER = 6;
    private volatile java.lang.Object low_;
    /**
     * <code>string low = 6;</code>
     * @return The low.
     */
    @java.lang.Override
    public java.lang.String getLow() {
      java.lang.Object ref = low_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        low_ = s;
        return s;
      }
    }
    /**
     * <code>string low = 6;</code>
     * @return The bytes for low.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLowBytes() {
      java.lang.Object ref = low_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        low_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(last_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, last_);
      }
      if (java.lang.Float.floatToRawIntBits(volume_) != 0) {
        output.writeFloat(3, volume_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(open_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, open_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(high_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, high_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(low_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, low_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(last_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, last_);
      }
      if (java.lang.Float.floatToRawIntBits(volume_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, volume_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(open_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, open_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(high_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, high_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(low_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, low_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nasdaq.historical.v1.Stock.NasdaqHistorical)) {
        return super.equals(obj);
      }
      nasdaq.historical.v1.Stock.NasdaqHistorical other = (nasdaq.historical.v1.Stock.NasdaqHistorical) obj;

      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getLast()
          .equals(other.getLast())) return false;
      if (java.lang.Float.floatToIntBits(getVolume())
          != java.lang.Float.floatToIntBits(
              other.getVolume())) return false;
      if (!getOpen()
          .equals(other.getOpen())) return false;
      if (!getHigh()
          .equals(other.getHigh())) return false;
      if (!getLow()
          .equals(other.getLow())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + LAST_FIELD_NUMBER;
      hash = (53 * hash) + getLast().hashCode();
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVolume());
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + getOpen().hashCode();
      hash = (37 * hash) + HIGH_FIELD_NUMBER;
      hash = (53 * hash) + getHigh().hashCode();
      hash = (37 * hash) + LOW_FIELD_NUMBER;
      hash = (53 * hash) + getLow().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nasdaq.historical.v1.Stock.NasdaqHistorical parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nasdaq.historical.v1.Stock.NasdaqHistorical prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nasdaq.historical.v1.NasdaqHistorical}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nasdaq.historical.v1.NasdaqHistorical)
        nasdaq.historical.v1.Stock.NasdaqHistoricalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nasdaq.historical.v1.Stock.internal_static_nasdaq_historical_v1_NasdaqHistorical_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nasdaq.historical.v1.Stock.internal_static_nasdaq_historical_v1_NasdaqHistorical_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nasdaq.historical.v1.Stock.NasdaqHistorical.class, nasdaq.historical.v1.Stock.NasdaqHistorical.Builder.class);
      }

      // Construct using nasdaq.historical.v1.Stock.NasdaqHistorical.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        date_ = "";

        last_ = "";

        volume_ = 0F;

        open_ = "";

        high_ = "";

        low_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nasdaq.historical.v1.Stock.internal_static_nasdaq_historical_v1_NasdaqHistorical_descriptor;
      }

      @java.lang.Override
      public nasdaq.historical.v1.Stock.NasdaqHistorical getDefaultInstanceForType() {
        return nasdaq.historical.v1.Stock.NasdaqHistorical.getDefaultInstance();
      }

      @java.lang.Override
      public nasdaq.historical.v1.Stock.NasdaqHistorical build() {
        nasdaq.historical.v1.Stock.NasdaqHistorical result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nasdaq.historical.v1.Stock.NasdaqHistorical buildPartial() {
        nasdaq.historical.v1.Stock.NasdaqHistorical result = new nasdaq.historical.v1.Stock.NasdaqHistorical(this);
        result.date_ = date_;
        result.last_ = last_;
        result.volume_ = volume_;
        result.open_ = open_;
        result.high_ = high_;
        result.low_ = low_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nasdaq.historical.v1.Stock.NasdaqHistorical) {
          return mergeFrom((nasdaq.historical.v1.Stock.NasdaqHistorical)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nasdaq.historical.v1.Stock.NasdaqHistorical other) {
        if (other == nasdaq.historical.v1.Stock.NasdaqHistorical.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getLast().isEmpty()) {
          last_ = other.last_;
          onChanged();
        }
        if (other.getVolume() != 0F) {
          setVolume(other.getVolume());
        }
        if (!other.getOpen().isEmpty()) {
          open_ = other.open_;
          onChanged();
        }
        if (!other.getHigh().isEmpty()) {
          high_ = other.high_;
          onChanged();
        }
        if (!other.getLow().isEmpty()) {
          low_ = other.low_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nasdaq.historical.v1.Stock.NasdaqHistorical parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nasdaq.historical.v1.Stock.NasdaqHistorical) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 1;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object last_ = "";
      /**
       * <code>string last = 2;</code>
       * @return The last.
       */
      public java.lang.String getLast() {
        java.lang.Object ref = last_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          last_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last = 2;</code>
       * @return The bytes for last.
       */
      public com.google.protobuf.ByteString
          getLastBytes() {
        java.lang.Object ref = last_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          last_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last = 2;</code>
       * @param value The last to set.
       * @return This builder for chaining.
       */
      public Builder setLast(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLast() {
        
        last_ = getDefaultInstance().getLast();
        onChanged();
        return this;
      }
      /**
       * <code>string last = 2;</code>
       * @param value The bytes for last to set.
       * @return This builder for chaining.
       */
      public Builder setLastBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        last_ = value;
        onChanged();
        return this;
      }

      private float volume_ ;
      /**
       * <code>float volume = 3;</code>
       * @return The volume.
       */
      @java.lang.Override
      public float getVolume() {
        return volume_;
      }
      /**
       * <code>float volume = 3;</code>
       * @param value The volume to set.
       * @return This builder for chaining.
       */
      public Builder setVolume(float value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float volume = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolume() {
        
        volume_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object open_ = "";
      /**
       * <code>string open = 4;</code>
       * @return The open.
       */
      public java.lang.String getOpen() {
        java.lang.Object ref = open_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          open_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string open = 4;</code>
       * @return The bytes for open.
       */
      public com.google.protobuf.ByteString
          getOpenBytes() {
        java.lang.Object ref = open_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          open_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string open = 4;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string open = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        
        open_ = getDefaultInstance().getOpen();
        onChanged();
        return this;
      }
      /**
       * <code>string open = 4;</code>
       * @param value The bytes for open to set.
       * @return This builder for chaining.
       */
      public Builder setOpenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        open_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object high_ = "";
      /**
       * <code>string high = 5;</code>
       * @return The high.
       */
      public java.lang.String getHigh() {
        java.lang.Object ref = high_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          high_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string high = 5;</code>
       * @return The bytes for high.
       */
      public com.google.protobuf.ByteString
          getHighBytes() {
        java.lang.Object ref = high_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          high_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string high = 5;</code>
       * @param value The high to set.
       * @return This builder for chaining.
       */
      public Builder setHigh(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string high = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh() {
        
        high_ = getDefaultInstance().getHigh();
        onChanged();
        return this;
      }
      /**
       * <code>string high = 5;</code>
       * @param value The bytes for high to set.
       * @return This builder for chaining.
       */
      public Builder setHighBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        high_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object low_ = "";
      /**
       * <code>string low = 6;</code>
       * @return The low.
       */
      public java.lang.String getLow() {
        java.lang.Object ref = low_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          low_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string low = 6;</code>
       * @return The bytes for low.
       */
      public com.google.protobuf.ByteString
          getLowBytes() {
        java.lang.Object ref = low_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          low_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string low = 6;</code>
       * @param value The low to set.
       * @return This builder for chaining.
       */
      public Builder setLow(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string low = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLow() {
        
        low_ = getDefaultInstance().getLow();
        onChanged();
        return this;
      }
      /**
       * <code>string low = 6;</code>
       * @param value The bytes for low to set.
       * @return This builder for chaining.
       */
      public Builder setLowBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        low_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nasdaq.historical.v1.NasdaqHistorical)
    }

    // @@protoc_insertion_point(class_scope:nasdaq.historical.v1.NasdaqHistorical)
    private static final nasdaq.historical.v1.Stock.NasdaqHistorical DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nasdaq.historical.v1.Stock.NasdaqHistorical();
    }

    public static nasdaq.historical.v1.Stock.NasdaqHistorical getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NasdaqHistorical>
        PARSER = new com.google.protobuf.AbstractParser<NasdaqHistorical>() {
      @java.lang.Override
      public NasdaqHistorical parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NasdaqHistorical(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NasdaqHistorical> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NasdaqHistorical> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nasdaq.historical.v1.Stock.NasdaqHistorical getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nasdaq_historical_v1_NasdaqHistorical_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nasdaq_historical_v1_NasdaqHistorical_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030com/redpanda/stock.proto\022\024nasdaq.histo" +
      "rical.v1\"g\n\020NasdaqHistorical\022\014\n\004date\030\001 \001" +
      "(\t\022\014\n\004last\030\002 \001(\t\022\016\n\006volume\030\003 \001(\002\022\014\n\004open" +
      "\030\004 \001(\t\022\014\n\004high\030\005 \001(\t\022\013\n\003low\030\006 \001(\tb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nasdaq_historical_v1_NasdaqHistorical_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nasdaq_historical_v1_NasdaqHistorical_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nasdaq_historical_v1_NasdaqHistorical_descriptor,
        new java.lang.String[] { "Date", "Last", "Volume", "Open", "High", "Low", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
